// ============================================================
// CoasterVerse Data — timeline, trivia, cards, facts
// ============================================================

/* ---------- TIMELINE ---------- */
export interface TimelineEntry {
  year: number;
  title: string;
  detail: string;
  kidDetail: string;
  kidHighlight?: boolean; // Show in kid mode "greatest hits"
  kidEmoji?: string; // Big emoji for kid card
  kidTitle?: string; // Fun kid-friendly title
}

export const timelineEntries: TimelineEntry[] = [
  { year: 1817, title: "Promenades Aériennes", detail: "The first wheeled roller coaster opens in Paris — riders descended a gentle slope on carts locked to a wooden track. The ride used gravity alone and reached roughly 30 mph.", kidDetail: "The very first roller coaster EVER! It was made of wood and went about as fast as a car in a parking lot. People in fancy clothes rode it for fun!", kidHighlight: true, kidEmoji: "🎢", kidTitle: "The Very First Coaster!" },
  { year: 1827, title: "Mauch Chunk Switchback Railway", detail: "A repurposed coal mine railway in Pennsylvania becomes a paid tourist attraction. The 9-mile gravity ride descended 2,322 feet of elevation at up to 50 mph.", kidDetail: "🏔️ A coal train in Pennsylvania became a roller coaster! People paid to ride a train DOWN a mountain — wheeee!" },
  { year: 1884, title: "Switchback Railway at Coney Island", detail: "LaMarcus Adna Thompson builds America's first purpose-built roller coaster at Coney Island. Riders paid 5¢ for a 6 mph ride down a 600-foot track.", kidDetail: "🎪 The first REAL roller coaster in America! It only cost a nickel and went slower than you can ride your bike!" },
  { year: 1895, title: "Flip Flap Railway", detail: "The first looping roller coaster. A perfectly circular loop produced up to 12 G of centripetal force — enough to cause neck injuries. Replaced quickly by the safer clothoid loop design.", kidDetail: "The first upside-down roller coaster! But OOPS — engineers made the loop a perfect circle, and it hurt people's necks! They had to learn to make egg-shaped loops instead.", kidHighlight: true, kidEmoji: "🔄", kidTitle: "First Loop... OUCH!" },
  { year: 1927, title: "The Cyclone — Coney Island", detail: "Designed by Vernon Keenan, the Cyclone opens at Coney Island with an 85-foot first drop at 60 mph. Its tight track and aggressive laterals make it legendary. Still operating today.", kidDetail: "🌀 The famous Cyclone opened at Coney Island! It's almost 100 years old and you can STILL ride it today!" },
  { year: 1959, title: "Matterhorn Bobsleds — Disneyland", detail: "The world's first tubular steel-track roller coaster. Arrow Development's innovation of bending steel tubes allowed smoother, more complex track shapes — the foundation of modern coasters.", kidDetail: "Walt Disney wanted a mountain at Disneyland with a coaster inside! Engineers invented smooth steel tubes to make it work. This invention changed coasters FOREVER — almost every coaster today uses this idea!", kidHighlight: true, kidEmoji: "🏰", kidTitle: "Disney Changed Everything!" },
  { year: 1975, title: "Corkscrew — Knott's Berry Farm", detail: "Arrow Dynamics installs the first modern inverting coaster with two corkscrews. Unlike the dangerous circular loops of the 1890s, these used clothoid geometry for safe 3–4 G inversions.", kidDetail: "🌀 The first coaster that turned you upside-down safely! Two corkscrews that spun you around — without hurting your neck!" },
  { year: 1976, title: "Revolution — Six Flags Magic Mountain", detail: "The first modern vertical loop on a coaster, designed by Anton Schwarzkopf. The loop used a teardrop/clothoid shape to keep G-forces between 3.5–4 G — thrilling but safe.", kidDetail: "⭕ The first big loop! It went straight up and over in a giant circle. Engineers made it egg-shaped so it felt amazing but safe!" },
  { year: 1989, title: "Magnum XL-200 — Cedar Point", detail: "Arrow Dynamics shatters the 200-foot barrier. At 205 ft tall and 72 mph, it inaugurates the 'hypercoaster' era. Its out-of-seat airtime redefined what coasters could deliver.", kidDetail: "The first coaster over 200 feet tall — that's taller than a 20-story building! Everyone thought it was IMPOSSIBLE to build something this big. It made you feel like you were flying out of your seat!", kidHighlight: true, kidEmoji: "🚀", kidTitle: "The Impossible Giant!" },
  { year: 1994, title: "Raptor — Cedar Point", detail: "B&M's inverted coaster suspends riders below the track with dangling feet. The 137-foot, 57 mph ride showed that inverted designs could be smooth, intense, and high-capacity.", kidDetail: "🦅 Your feet dangled in the air! You hung UNDER the track like a bird swooping through loops!" },
  { year: 2000, title: "Millennium Force — Cedar Point", detail: "Intamin's 310-foot, 93 mph giga coaster uses a cable lift hill and produces sustained floater airtime across its 6,595-foot layout. The first 'giga coaster' (300+ ft).", kidDetail: "🌟 The first coaster over 300 feet! That's like stacking 30 school buses on top of each other! It goes 93 mph — faster than most cars on the highway!" },
  { year: 2003, title: "Top Thrill Dragster — Cedar Point", detail: "Intamin's hydraulic launch catapults riders from 0 to 120 mph in 3.8 seconds up a 420-foot top hat. The first 'strata coaster' — over 400 feet tall.", kidDetail: "💨 Zero to 120 mph in less than 4 seconds! That's faster than a race car! Then you go over a 400-foot hill! INSANE!" },
  { year: 2005, title: "Kingda Ka — Six Flags Great Adventure", detail: "At 456 feet and 128 mph, Kingda Ka takes the height and speed records from Dragster. Uses a hydraulic launch generating 1.67 G of acceleration.", kidDetail: "The TALLEST roller coaster in the whole world! At 456 feet, it's taller than the Statue of Liberty! You launch from 0 to 128 mph in just 3 seconds, then go straight UP into the sky!", kidHighlight: true, kidEmoji: "👑", kidTitle: "The Tallest Ever!" },
  { year: 2010, title: "Formula Rossa — Ferrari World", detail: "A hydraulic-launched Intamin coaster reaching 149.1 mph — the fastest in the world. Riders wear goggles to protect from sand and insects at those speeds.", kidDetail: "The FASTEST roller coaster on Earth! It goes 149 mph — faster than a cheetah can run, faster than most race cars can drive! It's so fast you have to wear GOGGLES so bugs don't hit your eyes!", kidHighlight: true, kidEmoji: "🏎️", kidTitle: "The Fastest Ever!" },
  { year: 2012, title: "GateKeeper — Cedar Point", detail: "B&M's wing coaster places seats on either side of the track with nothing above or below. Riders experience a unique sensation of flight through its 170-foot keyhole element.", kidDetail: "✈️ You sit on the SIDE of the track with nothing above or below you! It feels like you're actually FLYING!" },
  { year: 2016, title: "Lightning Rod — Dollywood", detail: "RMC's launched wooden coaster — the first of its kind. A quad-down element delivers four consecutive moments of sustained airtime. Uses topper track on a wood structure.", kidDetail: "⚡ A WOODEN roller coaster with a launch! It pops you out of your seat FOUR times in a row!" },
  { year: 2018, title: "Steel Vengeance — Cedar Point", detail: "RMC converts the classic Mean Streak wooden coaster into a 205-foot hybrid with 30.4 seconds of airtime — more than any other coaster. Four inversions on a wood structure.", kidDetail: "🤠 They took an old wooden coaster and made it AMAZING! You feel weightless for over 30 seconds total — like being in space!" },
  { year: 2020, title: "Orion — Kings Island", detail: "B&M giga coaster with a 300-foot drop at 91 mph. Its compact 5,321-foot layout focuses on sustained negative-G parabolic hills.", kidDetail: "🪐 A 300-foot drop at 91 mph! The hills make you float out of your seat like an astronaut!" },
  { year: 2021, title: "Velocicoaster — Universal Orlando", detail: "Intamin's multi-launch masterpiece features a 155-foot top hat, zero-G stall, mosasaurus roll, and two LSM launches. Themed to Jurassic World with near-miss dinosaur encounters.", kidDetail: "A roller coaster where DINOSAURS chase you! You launch past real-looking velociraptors, go upside-down FOUR times, and feel like you're escaping from Jurassic World!", kidHighlight: true, kidEmoji: "🦖", kidTitle: "Dinosaur Escape!" },
  { year: 2023, title: "Iron Gwazi — Busch Gardens Tampa", detail: "RMC hybrid conversion reaching 76 mph with a 206-foot drop at 91 degrees (beyond vertical). 12 airtime moments in a 4,075-foot layout.", kidDetail: "🐊 This coaster drops you MORE than straight down — it actually tilts you past vertical! You get 12 moments of floating!" },
  { year: 2025, title: "Top Thrill 2 — Cedar Point", detail: "Zamperla rebuilds the legendary Top Thrill Dragster as a two-spike shuttle coaster. A new LSM launch system replaces the unreliable hydraulic motors, reaching 120 mph.", kidDetail: "🔥 They rebuilt one of the fastest coasters with NEW technology! It launches you at 120 mph using giant magnets!" },
  { year: 2026, title: "The Future", detail: "Active developments include magnetic launch systems exceeding 150 mph, VR-enhanced rides, adaptive track systems, and AI-designed track profiles optimized for airtime and smoothness.", kidDetail: "What comes next? Coasters that go even FASTER! Rides where you wear VR goggles and fly through space! Maybe even coasters that change their track every time you ride! What would YOUR dream coaster be?", kidHighlight: true, kidEmoji: "🔮", kidTitle: "What's Next?" },
];

/* ---------- TRIVIA ---------- */
export interface TriviaQuestion {
  question: string;
  options: string[];
  answer: number; // index
  funFact: string;
  kidQuestion?: string;
  kidOptions?: string[];
  kidFunFact?: string;
}

export const triviaQuestions: TriviaQuestion[] = [
  { question: "What is the fastest roller coaster in the world?", options: ["Kingda Ka", "Formula Rossa", "Top Thrill Dragster", "Do-Dodonpa"], answer: 1, funFact: "Formula Rossa at Ferrari World Abu Dhabi reaches 149.1 mph. Riders must wear goggles!", kidQuestion: "Which roller coaster is the FASTEST in the whole world?", kidOptions: ["Kingda Ka", "Formula Rossa 🏎️", "Top Thrill Dragster", "Do-Dodonpa"], kidFunFact: "Formula Rossa goes 149 mph — faster than a cheetah! 🐆" },
  { question: "What is the tallest roller coaster in the world?", options: ["Top Thrill 2", "Superman: Escape from Krypton", "Kingda Ka", "Fury 325"], answer: 2, funFact: "Kingda Ka stands at 456 feet — taller than the Statue of Liberty at 305 feet.", kidQuestion: "Which coaster is the TALLEST?", kidOptions: ["Top Thrill 2", "Superman", "Kingda Ka 👑", "Fury 325"], kidFunFact: "Kingda Ka is 456 feet tall — taller than the Statue of Liberty! 🗽" },
  { question: "What does RMC stand for in roller coaster manufacturing?", options: ["Ride Manufacturing Corp", "Rocky Mountain Construction", "Roller Motor Company", "Rail & Metal Coasters"], answer: 1, funFact: "Rocky Mountain Construction, founded by Fred Grubb, revolutionized the industry by converting rough wooden coasters into smooth hybrid steel-on-wood thrill machines.", kidQuestion: "What does RMC stand for? They make AWESOME coasters!", kidOptions: ["Ride Making Company", "Rocky Mountain Construction 🏔️", "Roller Motor Cars", "Really Mean Coasters"], kidFunFact: "Rocky Mountain Construction takes old bumpy wooden coasters and makes them SUPER smooth and fun! 🏔️" },
  { question: "What type of loop shape do modern coasters use instead of a perfect circle?", options: ["Parabola", "Clothoid (Euler spiral)", "Ellipse", "Catenary"], answer: 1, funFact: "A clothoid loop gradually tightens its radius, reducing max G-forces from 12+ G (circle) to a comfortable 3.5–5 G.", kidQuestion: "Why aren't roller coaster loops perfectly round?", kidOptions: ["They look cooler", "Egg shapes are safer for your body", "Round ones break", "No reason"], kidFunFact: "Round loops would squish you with too much force! Egg-shaped loops keep it fun AND safe! 🥚" },
  { question: "What year did the first tubular steel roller coaster open?", options: ["1955", "1959", "1963", "1972"], answer: 1, funFact: "The Matterhorn Bobsleds at Disneyland in 1959 used Arrow Development's tubular steel track — the technology behind every modern coaster.", kidQuestion: "Where was the FIRST modern roller coaster built?", kidOptions: ["Six Flags", "Disneyland 🏰", "Universal Studios", "Cedar Point"], kidFunFact: "Disneyland built the first modern coaster inside a fake mountain! 🏔️🏰" },
  { question: "How does a launched coaster's LSM (Linear Synchronous Motor) work?", options: ["Compressed air", "Alternating magnetic fields propel fin-equipped trains", "Hydraulic pistons", "Gravity assist"], answer: 1, funFact: "LSMs use precisely timed electromagnetic fields to pull metal fins on the train forward — like a linear version of an electric motor.", kidQuestion: "How do some coasters LAUNCH you super fast?", kidOptions: ["Air blows you", "Magnets push you! 🧲", "Springs shoot you", "You roll down a hill"], kidFunFact: "Giant magnets push the train forward like magic! ZOOM! 🧲" },
  { question: "What is 'airtime' on a roller coaster?", options: ["Time the ride operates daily", "The feeling of weightlessness over hills", "How long you're upside down", "Air resistance duration"], answer: 1, funFact: "Airtime occurs when you go over a hill fast enough that you experience less than 1 G — your body lifts off the seat. Enthusiasts measure it in seconds.", kidQuestion: "What's 'airtime' on a coaster?", kidOptions: ["When the ride opens", "Floating feeling over hills! 🎈", "Being upside-down", "Wind in your face"], kidFunFact: "It's when you go over a hill and your tummy floats — like the drop on a swing set, but BIGGER! 🎈" },
  { question: "What is the purpose of block brakes on a roller coaster?", options: ["To make the ride more thrilling", "To ensure two trains never occupy the same track section", "To slow down on turns", "To create special effects"], answer: 1, funFact: "Block brakes divide the track into sections. Only one train can be in each block at a time — this is how coasters safely run multiple trains.", kidQuestion: "Why do coasters have brakes in the middle of the ride?", kidOptions: ["To scare you", "So trains don't bump each other! 🚂", "To go slower on turns", "For fun"], kidFunFact: "The brakes make sure two trains NEVER crash into each other! Safety first! 🛑" },
  { question: "Which coaster has the most inversions?", options: ["Smiler (14)", "Colossus (10)", "Banshee (7)", "Montu (7)"], answer: 0, funFact: "The Smiler at Alton Towers holds the record with 14 inversions — riders go upside-down 14 times in a single ride!", kidQuestion: "Which coaster flips you upside-down the MOST times?", kidOptions: ["The Smiler - 14 times! 🔄", "Colossus - 10 times", "Banshee - 7 times", "Montu - 7 times"], kidFunFact: "The Smiler flips you upside-down 14 TIMES! Can you spin around 14 times? 🤪" },
  { question: "What is a 'stall' element on a roller coaster?", options: ["When the ride breaks down", "An inverted hang where you float inverted at low speed", "A type of brake", "A queue management technique"], answer: 1, funFact: "A zero-G stall rolls you inverted and holds you there at the apex with near-zero gravity — you hang from your restraint in pure weightlessness.", kidQuestion: "What's a 'stall' on a roller coaster?", kidOptions: ["The ride is broken", "You hang upside-down floating! 🙃", "A type of brake", "Where you wait in line"], kidFunFact: "You go upside-down and FLOAT there for a second — like being a bat! 🦇" },
  { question: "What material are most modern coaster wheels made of?", options: ["Rubber", "Polyurethane/Nylon", "Steel", "Ceramic"], answer: 1, funFact: "Modern coaster trains use three sets of polyurethane wheels per assembly: road wheels (on top), side-friction wheels, and up-stop wheels (underneath) to keep the train locked to the rail.", kidQuestion: "What are roller coaster wheels made of?", kidOptions: ["Rubber like a car", "Special plastic! 🛞", "Metal", "Glass"], kidFunFact: "Coaster wheels are made of special smooth plastic that makes the ride super smooth! 🛞" },
  { question: "What is the longest roller coaster in the world?", options: ["Steel Dragon 2000", "The Beast", "Fury 325", "Millennium Force"], answer: 0, funFact: "Steel Dragon 2000 at Nagashima Spa Land, Japan stretches 8,133 feet (1.54 miles) — you're on the track for over 4 minutes!", kidQuestion: "Which coaster is the LONGEST ride?", kidOptions: ["Steel Dragon 2000 🐉", "The Beast", "Fury 325", "Millennium Force"], kidFunFact: "Steel Dragon 2000 is so long the ride takes over 4 MINUTES! That's longer than most TV commercials! 🐉" },
  { question: "How do magnetic (eddy current) brakes work on coasters?", options: ["Friction pads on wheels", "Permanent magnets induce currents in metal fins, creating opposing force", "Electromagnets grab the train", "Air resistance panels"], answer: 1, funFact: "Eddy current brakes never touch the train — magnets induce currents in copper or aluminum fins that naturally oppose motion. They're failsafe: no power needed.", kidQuestion: "How do magnetic brakes slow down a coaster?", kidOptions: ["They squeeze the wheels", "Magnets slow you without touching! 🧲", "They grab the train", "Wind slows you down"], kidFunFact: "Magnetic brakes are like MAGIC — they slow you down without even touching the train! 🧲✨" },
  { question: "What is the term for a coaster that exceeds 300 feet tall?", options: ["Mega coaster", "Hyper coaster", "Giga coaster", "Strata coaster"], answer: 2, funFact: "Coaster classifications: Hyper (200+ ft), Giga (300+ ft), Strata (400+ ft). Millennium Force (2000) was the first giga coaster.", kidQuestion: "What do we call SUPER TALL coasters over 300 feet?", kidOptions: ["Mega coaster", "Hyper coaster", "Giga coaster 🦕", "Strata coaster"], kidFunFact: "Giga means GIANT! These coasters are as tall as 30 houses stacked up! 🏠🏠🏠" },
  { question: "What is a 'heartline roll'?", options: ["A banking turn", "A roll where the axis passes through the rider's heart/center of mass", "A loop named after its shape", "A type of launch"], answer: 1, funFact: "In a heartline roll, the track rotates around the rider's center of mass so they spin in place rather than being whipped around a wide arc. Extremely smooth sensation.", kidQuestion: "What's a 'heartline roll' on a coaster?", kidOptions: ["A turn", "You spin around your tummy! 💫", "A heart-shaped loop", "A type of launch"], kidFunFact: "The track spins around YOU so it feels super smooth — like doing a perfect somersault! 💫" },
  { question: "Which theme park has the most roller coasters?", options: ["Cedar Point", "Six Flags Magic Mountain", "Europa-Park", "Walt Disney World"], answer: 1, funFact: "Six Flags Magic Mountain holds the record with 20 roller coasters, narrowly beating Cedar Point's 17.", kidQuestion: "Which park has the MOST roller coasters?", kidOptions: ["Cedar Point", "Six Flags Magic Mountain 🏆", "Europa-Park", "Disney World"], kidFunFact: "Six Flags Magic Mountain has 20 coasters! You'd need 20 DAYS to ride them all once a day! 🎢🎢🎢" },
  { question: "What coaster was the first to use a hydraulic launch?", options: ["Xcelerator", "Top Thrill Dragster", "Storm Runner", "Kingda Ka"], answer: 0, funFact: "Xcelerator at Knott's Berry Farm (2002) was the first Intamin hydraulic launch coaster, reaching 82 mph in 2.3 seconds.", kidQuestion: "Which coaster was FIRST to launch you like a rocket?", kidOptions: ["Xcelerator 🚀", "Top Thrill Dragster", "Storm Runner", "Kingda Ka"], kidFunFact: "Xcelerator goes 0 to 82 mph in just 2 seconds! That's faster than a sports car! 🚀" },
  { question: "What does a 'trim brake' do?", options: ["Stops the train completely", "Slightly reduces speed at specific points", "Trims the track length", "Adjusts the lap bar"], answer: 1, funFact: "Trim brakes reduce speed slightly at key points to manage forces and ride timing. Enthusiasts often dislike them because they reduce airtime.", kidQuestion: "What does a 'trim brake' do on a coaster?", kidOptions: ["Stops the train", "Slows you down a little bit 🐢", "Cuts the track", "Tightens your seatbelt"], kidFunFact: "Trim brakes slow you down just a TINY bit to keep the ride safe! 🐢" },
  { question: "What roller coaster type has riders standing up?", options: ["Floorless", "Stand-up", "Wing", "Inverted"], answer: 1, funFact: "Stand-up coasters by B&M were popular in the 90s but fell out of favor due to discomfort. Many have been converted to floorless sit-down coasters.", kidQuestion: "What type of coaster do you ride STANDING UP?", kidOptions: ["Floorless", "Stand-up coaster! 🧍", "Wing coaster", "Inverted"], kidFunFact: "You ride the whole thing standing on your feet! It's like surfing through the sky! 🧍🏄" },
  { question: "What is the purpose of the chain dog on a lift hill?", options: ["Decorative element", "Anti-rollback device that prevents the train from sliding backwards", "Connects the chain links", "A mascot name"], answer: 1, funFact: "The clicking sound you hear going up a lift hill is the anti-rollback dog catching on teeth in the track — if the chain breaks, the dog locks and holds the train.", kidQuestion: "What makes the CLICK-CLICK-CLICK sound going up a hill?", kidOptions: ["The wheels", "Safety clickers that stop you rolling back! 🔒", "The engine", "People clapping"], kidFunFact: "Those clicks are like a bike lock - they stop the train from rolling backwards if the chain breaks! CLICK CLICK CLICK! 🔒" },
  { question: "What is 'tracking' in coaster enthusiast terminology?", options: ["Following a coaster's location", "How smoothly the train navigates transitions", "Mapping a coaster's path", "Recording ride footage"], answer: 1, funFact: "Good tracking means smooth, jerk-free transitions between elements. Poor tracking causes vibration and head-banging — a major complaint about rough coasters.", kidQuestion: "What does 'tracking' mean for a coaster?", kidOptions: ["Where it's located", "How smooth the ride is! 🧈", "Drawing a map", "Filming the ride"], kidFunFact: "Good tracking means a smooth ride! Bad tracking means your head bounces around — ouch! 🧈" },
  { question: "What is the steepest drop angle on any coaster?", options: ["90°", "95°", "97°", "Beyond vertical — some exceed 100°"], answer: 3, funFact: "Several coasters feature beyond-vertical drops (past 90°). TMNT Shellraiser has a 121.5° drop — you actually lean forward past straight down!", kidQuestion: "Can roller coasters drop you MORE than straight down?", kidOptions: ["No way!", "Yes - past straight down! 🤯", "Only a little", "That's impossible"], kidFunFact: "Some coasters tilt you PAST straight down! You lean forward into the drop! AHHHH! 🤯" },
  { question: "Which manufacturer pioneered the 'wing coaster' design?", options: ["Intamin", "Vekoma", "B&M (Bolliger & Mabillard)", "Mack Rides"], answer: 2, funFact: "B&M introduced wing coasters where riders sit on either side of the track with nothing above or below — creating a sensation of flight.", kidQuestion: "Who invented the 'wing coaster' where you fly on the side?", kidOptions: ["Intamin", "Vekoma", "B&M ✈️", "Mack Rides"], kidFunFact: "On a wing coaster, you sit on the SIDE with nothing above or below you — like flying! ✈️" },
  { question: "What are 'laterals' on a roller coaster?", options: ["Side-to-side forces pushing you into the restraint", "Vertical drops", "A type of inversion", "Side-mounted cameras"], answer: 0, funFact: "Strong laterals push you sideways in your seat during unbanked turns. Some coasters are famous for aggressive laterals — the Cyclone at Coney Island is a prime example.", kidQuestion: "What are 'laterals' on a coaster?", kidOptions: ["Getting pushed sideways! ↔️", "Going straight down", "Going upside-down", "Cameras on the side"], kidFunFact: "Laterals are when turns push you sideways into your friend sitting next to you! Squish! ↔️" },
  { question: "How fast can a hydraulic launch accelerate a coaster train?", options: ["0-60 in 5 seconds", "0-120 mph in under 4 seconds", "0-80 in 10 seconds", "0-50 in 2 seconds"], answer: 1, funFact: "Top Thrill Dragster's hydraulic launch went from 0 to 120 mph in 3.8 seconds — that's faster than a fighter jet catapult launch from an aircraft carrier!", kidQuestion: "How fast can a launched coaster go from zero?", kidOptions: ["0-60 in 5 seconds", "0-120 mph in under 4 seconds! 💨", "0-80 in 10 seconds", "0-50 in 2 seconds"], kidFunFact: "Some coasters go from standing still to 120 mph in less than 4 seconds! WHOOOOSH! 💨" },
  { question: "What does B&M stand for?", options: ["Busch & Merlin", "Bolliger & Mabillard", "Berg & Miller", "Brakes & Motors"], answer: 1, funFact: "Walter Bolliger and Claude Mabillard, Swiss engineers, founded B&M in 1988. They're responsible for many of the world's most popular coasters including Fury 325, Banshee, and Montu.", kidQuestion: "What does B&M stand for? (They build AMAZING coasters!)", kidOptions: ["Busch & Merlin", "Bolliger & Mabillard 🇨🇭", "Berg & Miller", "Brakes & Motors"], kidFunFact: "Two guys from Switzerland named Bolliger and Mabillard build some of the BEST coasters in the world! 🇨🇭" },
  { question: "What is the world's oldest operating roller coaster?", options: ["Cyclone (1927)", "Leap-the-Dips (1902)", "Jack Rabbit (1920)", "Giant Dipper (1924)"], answer: 1, funFact: "Leap-the-Dips at Lakemont Park, Pennsylvania opened in 1902 and is a National Historic Landmark. It's a side-friction figure-eight design that reaches just 10 mph.", kidQuestion: "How OLD is the oldest roller coaster you can still ride?", kidOptions: ["50 years old", "Over 120 years old! 👴", "80 years old", "25 years old"], kidFunFact: "Leap-the-Dips is over 120 years old! Your great-great-great grandparents could have ridden it! 👴" },
  { question: "What innovation did Arrow Dynamics contribute to coasters?", options: ["Wooden track", "Tubular steel track and the modern looping coaster", "Hydraulic launches", "Magnetic brakes"], answer: 1, funFact: "Arrow Dynamics invented tubular steel track (Matterhorn 1959) and the modern loop (Corkscrew 1975). They made the modern coaster era possible.", kidQuestion: "What amazing thing did Arrow Dynamics invent?", kidOptions: ["Wood tracks", "Steel track AND loops! 🔄", "Super fast launches", "Magnetic brakes"], kidFunFact: "Arrow Dynamics invented the smooth steel track AND the first safe loop! They made modern coasters possible! 🔄" },
  { question: "What is 'stapling' in coaster lingo?", options: ["Fixing track sections", "When a ride operator pushes your restraint too tight", "A construction technique", "Attaching the chain"], answer: 1, funFact: "Getting 'stapled' means the ride operator pushed your lap bar down extra tight, reducing your airtime. Enthusiasts dread it!", kidQuestion: "What does 'stapled' mean on a coaster?", kidOptions: ["Fixing the track", "Lap bar pushed down too tight! 😫", "Building it", "Hooking up the chain"], kidFunFact: "Getting 'stapled' means the lap bar is pushed down super tight — you can't float on the hills! 😫" },
  { question: "What is a 'flying coaster'?", options: ["A coaster with wings", "Riders are face-down in a prone (Superman) position", "A coaster that goes over water", "A launched coaster"], answer: 1, funFact: "Flying coasters like Tatsu and Manta rotate riders face-down so you soar through elements like Superman. B&M and Vekoma both make flying models.", kidQuestion: "What's a 'flying coaster'?", kidOptions: ["Has wings on the side", "You fly face-down like Superman! 🦸", "Goes over water", "Goes really fast"], kidFunFact: "You lie down facing the ground and FLY through the air like Superman! Up, up, and away! 🦸" },
];

/* ---------- COASTER CARDS ---------- */
export type Rarity = "Common" | "Rare" | "Legendary";

export interface CoasterCard {
  id: string;
  name: string;
  park: string;
  year: number;
  type: "Wood" | "Steel" | "Hybrid" | "Launched";
  speed: number; // mph
  height: number; // feet
  length: number; // feet
  inversions: number;
  thrillRating: number; // 1–10
  rarity: Rarity;
  unlockMethod: string; // how to unlock
  kidComparison: string;
}

export const coasterCards: CoasterCard[] = [
  { id: "millennium-force", name: "Millennium Force", park: "Cedar Point", year: 2000, type: "Steel", speed: 93, height: 310, length: 6595, inversions: 0, thrillRating: 9, rarity: "Legendary", unlockMethod: "Visit 3 days", kidComparison: "As tall as a 30-story building!" },
  { id: "steel-vengeance", name: "Steel Vengeance", park: "Cedar Point", year: 2018, type: "Hybrid", speed: 74, height: 205, length: 5740, inversions: 4, thrillRating: 10, rarity: "Legendary", unlockMethod: "Complete 5 trivia", kidComparison: "You float for 30 whole seconds — like being in space!" },
  { id: "velocicoaster", name: "Velocicoaster", park: "Universal Orlando", year: 2021, type: "Launched", speed: 70, height: 155, length: 4700, inversions: 4, thrillRating: 10, rarity: "Legendary", unlockMethod: "Build 3 coasters", kidComparison: "Dinosaurs chase you at 70 mph!" },
  { id: "fury-325", name: "Fury 325", park: "Carowinds", year: 2015, type: "Steel", speed: 95, height: 325, length: 6602, inversions: 0, thrillRating: 9, rarity: "Rare", unlockMethod: "Complete 3 trivia", kidComparison: "Taller than the Statue of Liberty!" },
  { id: "the-beast", name: "The Beast", park: "Kings Island", year: 1979, type: "Wood", speed: 65, height: 135, length: 7359, inversions: 0, thrillRating: 8, rarity: "Rare", unlockMethod: "default", kidComparison: "The longest wooden coaster — it goes through the FOREST at night!" },
  { id: "kingda-ka", name: "Kingda Ka", park: "Six Flags Great Adventure", year: 2005, type: "Launched", speed: 128, height: 456, length: 3118, inversions: 0, thrillRating: 9, rarity: "Legendary", unlockMethod: "Visit 5 days", kidComparison: "128 mph — faster than a cheetah AND a race car!" },
  { id: "el-toro", name: "El Toro", park: "Six Flags Great Adventure", year: 2006, type: "Wood", speed: 70, height: 181, length: 4400, inversions: 0, thrillRating: 9, rarity: "Rare", unlockMethod: "Complete 1 trivia", kidComparison: "The most airtime on any wooden coaster!" },
  { id: "iron-gwazi", name: "Iron Gwazi", park: "Busch Gardens Tampa", year: 2022, type: "Hybrid", speed: 76, height: 206, length: 4075, inversions: 3, thrillRating: 10, rarity: "Rare", unlockMethod: "Build 1 coaster", kidComparison: "Drops you PAST straight down!" },
  { id: "formula-rossa", name: "Formula Rossa", park: "Ferrari World", year: 2010, type: "Launched", speed: 149, height: 171, length: 6562, inversions: 0, thrillRating: 8, rarity: "Legendary", unlockMethod: "Complete 10 trivia", kidComparison: "149 mph! You need GOGGLES to ride!" },
  { id: "the-cyclone", name: "The Cyclone", park: "Coney Island", year: 1927, type: "Wood", speed: 60, height: 85, length: 2640, inversions: 0, thrillRating: 7, rarity: "Common", unlockMethod: "default", kidComparison: "Almost 100 years old and still awesome!" },
  { id: "matterhorn", name: "Matterhorn Bobsleds", park: "Disneyland", year: 1959, type: "Steel", speed: 27, height: 80, length: 2134, inversions: 0, thrillRating: 5, rarity: "Common", unlockMethod: "default", kidComparison: "The coaster that started it ALL!" },
  { id: "x2", name: "X2", park: "Six Flags Magic Mountain", year: 2002, type: "Steel", speed: 76, height: 200, length: 3610, inversions: 2, thrillRating: 9, rarity: "Rare", unlockMethod: "Visit 2 days", kidComparison: "Your seat SPINS while you ride! Total chaos!" },
  { id: "lightning-rod", name: "Lightning Rod", park: "Dollywood", year: 2016, type: "Hybrid", speed: 73, height: 165, length: 3800, inversions: 0, thrillRating: 9, rarity: "Rare", unlockMethod: "Build 2 coasters", kidComparison: "A wooden coaster with a LAUNCH — the first ever!" },
  { id: "expedition-everest", name: "Expedition Everest", park: "Disney's Animal Kingdom", year: 2006, type: "Steel", speed: 50, height: 199, length: 4424, inversions: 0, thrillRating: 7, rarity: "Common", unlockMethod: "default", kidComparison: "You go BACKWARDS away from a Yeti!" },
  { id: "top-thrill-2", name: "Top Thrill 2", park: "Cedar Point", year: 2025, type: "Launched", speed: 120, height: 420, length: 2800, inversions: 0, thrillRating: 10, rarity: "Legendary", unlockMethod: "Complete 7 trivia", kidComparison: "120 mph using MAGNETS! The future is here!" },
  { id: "the-smiler", name: "The Smiler", park: "Alton Towers", year: 2013, type: "Steel", speed: 53, height: 98, length: 3838, inversions: 14, thrillRating: 8, rarity: "Rare", unlockMethod: "Complete 2 trivia", kidComparison: "14 times upside-down! More than ANY other coaster!" },
  // Birthday cards
  { id: "class-of-88", name: "Class of '88", park: "Special Edition", year: 1988, type: "Steel", speed: 76, height: 170, length: 4000, inversions: 3, thrillRating: 8, rarity: "Legendary", unlockMethod: "birthday-april", kidComparison: "From the year coasters got SERIOUS! Vortex opened with 6 loops!" },
  { id: "born-to-ride", name: "Born to Ride", park: "Special Edition", year: 2019, type: "Hybrid", speed: 80, height: 200, length: 5000, inversions: 4, thrillRating: 10, rarity: "Legendary", unlockMethod: "birthday-october", kidComparison: "The year YOU were born, coasters were the best EVER!" },
];

/* ---------- FACTS ---------- */
export const coasterFacts: string[] = [
  "The first roller coasters were ice slides in 17th-century Russia — riders sat on blocks of ice and slid down 70-foot wooden ramps!",
  "Cedar Point in Ohio is known as the 'Roller Coaster Capital of the World' with 17 coasters.",
  "The average roller coaster train weighs about 20,000 pounds fully loaded with riders.",
  "Roller coaster wheels come in sets of three: road wheels on top, side-friction wheels, and up-stop wheels underneath to prevent derailment.",
  "The clicking sound on a lift hill is the anti-rollback device — ratcheting teeth that prevent the train from sliding backwards.",
  "Formula Rossa accelerates so fast that riders must wear protective goggles against sand and insects.",
  "Steel Vengeance at Cedar Point has 30.4 seconds of airtime — the most of any coaster in the world.",
  "B&M (Bolliger & Mabillard) was founded by two Swiss engineers who previously worked at Intamin.",
  "Wooden roller coasters can expand up to 6 inches in hot weather due to thermal expansion of the lumber.",
  "The Smiler at Alton Towers holds the world record for most inversions: 14 in a single ride.",
  "Magnetic brakes on modern coasters never actually touch the train — they use eddy currents to slow it contactlessly.",
  "A rider on a roller coaster typically experiences between 3 and 6 G of force — fighter pilots experience similar loads.",
  "The chain on a typical lift hill moves at about 11–14 mph, but some high-speed lifts can reach 20+ mph.",
  "Roller coaster track is manufactured in sections and assembled on-site like a giant 3D puzzle.",
  "Intamin's hydraulic launch system can produce over 10,000 horsepower — more than 10 Formula 1 cars combined.",
  "The world's longest wooden coaster, The Beast, is 7,359 feet — nearly 1.4 miles of track through the woods.",
  "RMC (Rocky Mountain Construction) converts old rough wooden coasters into smooth hybrid thrill machines using steel-on-wood 'IBox' track.",
  "Walt Disney's Matterhorn Bobsleds (1959) was the world's first tubular steel coaster — the tech behind every modern coaster.",
  "Some coasters use water brakes — a scoop on the train dips into a trough of water at the end of the ride.",
  "The tallest roller coaster, Kingda Ka, is 456 feet tall — taller than the Great Pyramid of Giza (449 feet).",
  "A coaster train's polyurethane wheels are replaced every 1–3 days during peak season due to wear.",
  "The 'heartline' of a coaster is the imaginary line through the rider's center of mass — inversions designed around it feel smoother.",
  "Night rides are considered the best by enthusiasts because you can't see the track ahead — every element is a surprise.",
  "Arrow Dynamics invented both the tubular steel track AND the modern corkscrew inversion in the 1970s.",
  "Some coaster engineers use NASA-grade simulation software to model G-forces and rider biomechanics.",
  "The record for most coasters ridden in 24 hours is 78, achieved at multiple parks with precise scheduling.",
  "Velocicoaster at Universal Orlando cost an estimated $200 million to build — one of the most expensive coasters ever.",
];

/* ---------- KID-FRIENDLY FACTS ---------- */
export const kidFacts: string[] = [
  "🧊 The first roller coasters were made of ICE in Russia! People slid down giant ice ramps!",
  "🎢 Cedar Point has 17 roller coasters — imagine riding a different one for each day!",
  "🐘 A roller coaster train full of people weighs as much as TWO elephants!",
  "🔊 That click-click-click going up the hill? Those are safety teeth that stop the train from rolling back!",
  "🦟 Formula Rossa is SO fast you need goggles so bugs don't hit your face!",
  "🪶 Steel Vengeance makes you feel weightless for 30 seconds total — like floating in space!",
  "🇨🇭 B&M coasters are designed by Swiss engineers — the same country that makes great chocolate AND great coasters!",
  "🌡️ Wooden coasters grow taller in summer because the wood expands in the heat!",
  "🔄 The Smiler flips you upside-down 14 TIMES! Can you spin around 14 times without getting dizzy?",
  "🧲 Magnetic brakes slow down coasters WITHOUT touching them — like magic!",
  "🧑‍🚀 Riding a coaster can feel like being an astronaut — you experience the same forces as a rocket launch!",
  "⛓️ The chain pulling you up a hill moves about as fast as you ride your bike!",
  "🧩 Coaster tracks are built in pieces and put together like a GIANT puzzle!",
  "🏎️ A coaster's launch engine is more powerful than TEN race cars!",
  "🌲 The Beast goes through actual WOODS — it's like a coaster through a forest!",
  "🏰 Disneyland's Matterhorn was the FIRST modern roller coaster — thanks, Walt Disney!",
  "💦 Some coasters stop using a giant pool of water — the train's scoop splashes into it!",
  "🏛️ Kingda Ka is taller than the Great Pyramid in Egypt!",
  "🌙 Riding at NIGHT is the best — you can't see what's coming next! SURPRISE!",
  "👷 Coaster engineers use the same computer programs as NASA rocket scientists!",
  "🏆 Someone rode 78 different coasters in ONE DAY! That's a world record!",
  "🦖 Velocicoaster cost 200 MILLION dollars to build! That's a LOT of allowance money!",
  "💨 The fastest coaster goes 149 mph — a cheetah only goes 70! 🐆",
  "🎵 Coasters make music! Each part of the track creates different sounds as the train zooms over it!",
  "⚡ Lightning Rod at Dollywood is a wooden coaster that LAUNCHES you — the first one ever!",
];
